#!/bin/bash
# Script para iniciar el sistema AFRA-I

ok=0
error=1

# Funciones

# $1: Mensaje a loguear ; $2: Tipo del mensaje
function grabar_en_log {
    $BINDIR/GraLog.sh AFRAINIC "$1" "$2"
}

# /Funciones

# Verificar si el ambiente ya fue inicializado
if [ "$MAEDIR" != "" ] ; then
    grabar_en_log "El ambiente ya fue inicializado. Para reiniciar termine la sesión y ejecute AFRAINIC nuevamente." "WAR"
    echo "El ambiente ya fue inicializado. Para reiniciar termine la sesión y ejecute AFRAINIC nuevamente."
    return $ok
fi

# Buscar path GRUPO
while [ ! -f AFRAINST ] && [ $PWD != "/" ] ; do # Buscar AFRAINST
    cd ..
done

# Si no se encontro AFRAINST salir
if [ ! -f AFRAINST ] && [ $PWD == "/" ] ; then
    echo "No se pudo encontrar AFRAINST en el directorio raíz. Descomprima el paquete de instalación nuevamente."
    return $error
fi

export GRUPO=$PWD # Tengo el directorio raiz
export CONFDIR="$GRUPO/conf"

# Verificar si existe el archivo de configuración
if ! [ -d "$CONFDIR" ] ; then
    echo "No existe directorio de configuración. Descomprima el paquete de instalación nuevamente."
    return $error
fi
if ! [ -f "$CONFDIR/AFRAINST.conf" ] ; then
    echo "AFRA-I no está adecuadamente instalado en el sistema. Ejecute AFRAINST."
    return $error
fi

# Cargo valores del archivo de configuracion
export BINDIR=`grep BINDIR "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
MAEDIR=`grep MAEDIR "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2` # Exporto MAEDIR al final, cuando AFRAINIC termina correctamente
export NOVEDIR=`grep NOVEDIR "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
export ACEPDIR=`grep ACEPDIR "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
export PROCDIR=`grep PROCDIR "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
export REPODIR=`grep REPODIR "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
export LOGDIR=`grep LOGDIR "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
export RECHDIR=`grep RECHDIR "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
export DATASIZE=`grep DATASIZE "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
export LOGSIZE=`grep LOGSIZE "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
export LOGEXT=`grep LOGEXT "$CONFDIR/AFRAINST.conf" | cut -d '=' -f 2`
cd "$BINDIR"

# Verificar instalacion completa
estado_instalacion=COMPLETA
faltantes_bindir=()
faltantes_maedir=()
faltantes_directorios=()

if ! [ -d "$BINDIR" ] ; then
    faltantes_directorios+=("Ejecutables")
else
    # Verificar presencia de ejecutables
    archivos_bindir=$(ls "$BINDIR")
    archivos=("GraLog.sh" "MoverA.sh" "Arrancar.sh" "Detener.sh" "AFRAINIC" "AFRARECI" "AFRAUMBR" "AFRALIST")
    for archivo in ${archivos[@]} ; do
        if ! [[ "$archivos_bindir" =~ (^|[[:space:]])"$archivo"($|[[:space:]]) ]] ; then
            faltantes_bindir+=("$archivo")
        fi
    done
fi

if ! [ -d "$MAEDIR" ] ; then
    faltantes_directorios+=("Maestros")
else
    # Verificar presencia de maestros y tablas
    archivos_maedir=$(ls "$MAEDIR")
    archivos=("CdP.mae" "CdA.mae" "CdC.mae" "agentes.mae" "tllama.tab" "umbral.tab")
    for archivo in ${archivos[@]} ; do
        if ! [[ "$archivos_maedir" =~ (^|[[:space:]])"$archivo"($|[[:space:]]) ]] ; then
            faltantes_maedir+=("$archivo")
        fi
    done
fi

if ! [ -d "$NOVEDIR" ] ; then
    faltantes_directorios+=("Novedades")
fi
if ! [ -d "$ACEPDIR" ] ; then
    faltantes_directorios+=("Aceptados")
fi
if ! [ -d "$PROCDIR" ] ; then
    faltantes_directorios+=("Sospechosos")
fi
if ! [ -d "$REPODIR" ] ; then
    faltantes_directorios+=("Reportes")
fi
if ! [ -d "$LOGDIR" ] ; then
    faltantes_directorios+=("Logs")
fi
if ! [ -d "$RECHDIR" ] ; then
    faltantes_directorios+=("Rechazados")
fi

if [ "$faltantes_bindir" != "" ] || [ "$faltantes_maedir" != "" ] || [ "$faltantes_directorios" != "" ] ; then
    echo "La instalación de AFRA-I no está completa."
    echo
    if [ "$faltantes_bindir" != "" ] || [ "$faltantes_maedir" != "" ] ; then
        echo -n "Componentes faltantes: "
        for elemento in ${faltantes_bindir[@]} ; do
            echo -n "$elemento "
        done
        for elemento in ${faltantes_maedir[@]} ; do
            echo -n "$elemento "
        done
        echo
        echo "Para reparar esto debe ejecutar AFRAINST y seguir los pasos allí especificados."
    fi
    if [ "$faltantes_directorios" != "" ] ; then
        echo -n "Directorios faltantes: "
        for elemento in ${faltantes_directorios[@]} ; do
            echo -n "$elemento "
        done
        echo
        echo "Para reparar esto debe borrar el archivo \"AFRAINST.conf\" en el directorio $CONFDIR, y luego ejecutar AFRAINST para realizar la instalación de AFRA-I nuevamente."
    fi
    return $error
fi

# Verificar permisos
archivos=("$BINDIR/AFRARECI" "$BINDIR/AFRAUMBR" "$BINDIR/AFRALIST" "$BINDIR/Arrancar.sh" "$BINDIR/Detener.sh" "$BINDIR/GraLog.sh" "$BINDIR/MoverA.sh" "$MAEDIR/CdP.mae" "$MAEDIR/CdA.mae" "$MAEDIR/CdC.mae" "$MAEDIR/agentes.mae" "$MAEDIR/tllama.tab" "$MAEDIR/umbral.tab")
for archivo in ${archivos[@]} ; do
    if [ ! -x "$archivo" ] || [ ! -r "$archivo" ] ; then # Si no se puede leer o ejecutar
        chmod -f 777 "$archivo"
        if [ ! -x "$archivo" ] || [ ! -r "$archivo" ] ; then
            grabar_en_log "No es posible cambiar los permisos del archivo $archivo." "ERR"
            echo "No es posible cambiar los permisos del archivo $archivo."
            return $error
        fi
    fi
done

# Inicializar ambiente
echo "Directorio de configuración: $CONFDIR"
archivos_confdir=$(ls "$CONFDIR")
grabar_en_log "Directorio de configuración: $CONFDIR $archivos_confdir" "INFO"
ls "$CONFDIR"
echo
echo "Directorio de ejecutables: $BINDIR"
archivos_bindir=$(ls "$BINDIR")
grabar_en_log "Directorio de ejecutables: $BINDIR $archivos_bindir" "INFO"
ls "$BINDIR"
echo
echo "Directorio de maestros y tablas: $MAEDIR"
archivos_maedir=$(ls "$MAEDIR")
grabar_en_log "Directorio de maestros y tablas: $MAEDIR $archivos_maedir" "INFO"
ls "$MAEDIR"
echo
grabar_en_log "Directorio de recepción de archivos de llamadas: $NOVEDIR" "INFO"
echo "Directorio de recepción de archivos de llamadas: $NOVEDIR"
echo
grabar_en_log "Directorio de archivos de llamadas aceptadas: $ACEPDIR" "INFO"
echo "Directorio de archivos de llamadas aceptadas: $ACEPDIR"
echo
grabar_en_log "Directorio de archivos de llamadas sospechosas: $PROCDIR" "INFO"
echo "Directorio de archivos de llamadas sospechosas: $PROCDIR"
echo
grabar_en_log "Directorio de archivos de reportes de llamadas: $REPODIR" "INFO"
echo "Directorio de archivos de reportes de llamadas: $REPODIR"
echo
echo "Directorio de archivos de log: $LOGDIR"
archivos_logdir=$(ls "$LOGDIR")
grabar_en_log "Directorio de archivos de log: $LOGDIR $archivos_logdir" "INFO"
ls "$LOGDIR"
echo
grabar_en_log "Directorio de archivos rechazados: $RECHDIR" "INFO"
echo "Directorio de archivos rechazados: $RECHDIR"
echo
grabar_en_log "Estado del sistema: INICIALIZADO" "INFO"
echo "Estado del sistema: INICIALIZADO"
echo
export MAEDIR # El ambiente queda inicializado

# Arrancar AFRARECI
while [ "$opcion" != Si ] ; do
    echo -n "¿Desea ejecutar el demonio AFRARECI? (Si-No): "
    read opcion
    grabar_en_log "¿Desea ejecutar el demonio AFRARECI? (Si-No): $opcion" "INFO"
    if [ -z "$opcion" ] ; then
        opcion=Si # Opcion por default
    fi
    if [ "$opcion" == No ] ; then
        echo "Para ejecutar el demonio AFRARECI utilice el siguiente comando: ./Arrancar.sh AFRARECI"
        return $error
    fi
done
"$BINDIR/Arrancar.sh" AFRARECI
